name: Doc to PDF

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1: Checkout code from repository
      - name: Checkout repo
        uses: actions/checkout@v7

      # 2: Install pandoc dependencies
      - name: Install dependencies
        run: sudo apt install texlive texlive-latex-extra pandoc

      # 3: Convert
      - name: Convert Markdown to PDF
        run: pandoc README.md -o README.pdf

      # # 3: Install pandoc and convert md to pdf
      # - name: Conversion
      #   uses: docker://pandoc/core:latest
      #   with:
      #     args: >-
      #       -o README.pdf
      #       README.md

      # 4: Upload generated PDF as artifact
      - name: Upload Documentation
        uses: actions/upload-artifact@v7
        with:
          name: Resume
          path: ./README.pdf
