name: Doc to PDF

# Add permissions
permissions:
  actions: write
  contents: write

# Specify branch
on: 
  push:
    tags:
      - 'v*.*'

# Start job
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref }}
    steps:
      # 1: Checkout code from repository
      - name: checkout repo
        uses: actions/checkout@v7

      # 2: Install pandoc dependencies
      - name: install Dependencies
        run: |
          sudo apt update
          sudo apt install texlive texlive-latex-extra pandoc

      # 3: Generate tag
      - name: generate tag
        run: |
          echo "timestamp=$(date +%F)" >> "GITHUB_ENV"

      # 4: Push tag
      - name: push tag
        uses: actions/github-script@v9
        with:
          script: |
            const {timestamp} = process.env
            const version = process.env.VERSION
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `${version}-${timestamp}`,
              sha: context.sha
            })
            console.log(timestamp)

      # 5: Convert MD to PDF
      - name: convert markdown to pdf
        run: pandoc -V geometry:margin=0.75in README.md -o Resume.pdf

      - name: publish release and clean draft tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create $version Resume.pdf
          for draft in $(gh release list --limit 999 |grep -i draft | cut -f 1); do \
            gh release delete $draft; \
          done

      # 6: Upload generated PDF as artifact
      - name: store artifact
        uses: actions/upload-artifact@v7
        with:
          name: Resume
          path: ./Resume.pdf
