name: Scripting

run-name: Scripting

# Add permissions
permissions:
  actions: write
  contents: write

# Specify branch
on: 
  push:
    branches: 
      - dev

# Job start
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1: Checkout code from repository
      - name: checkout repo
        uses: actions/checkout@v7

      # 2: Make a release
      - name: generate draft tag
        run: |
          echo "timestamp=$(date +%F-%H-%M-%S)-draft" >> "$GITHUB_ENV"
          echo "nano=$(date +%N)" >> "$GITHUB_ENV"

      - name: push tag
        uses: actions/github-script@v9
        env:
          JERRY: ${{ github.ref_name }}
          NOBODY: ${{ github.ref }}
        with:
          script: |
            const timestamp = process.env.timestamp
            const nano = process.env.nano
            const jerry = process.env.JERRY
            const nobody = process.env.NOBODY
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${timestamp}-${nano}`,
              sha: context.sha
            })

            console.log(`Timestamp: ${timestamp}`)
            console.log(`Nano: ${nano}`)
            console.log(`Jerry: ${jerry}`)
            console.log(`Nobody: ${nobody}`)

